### ISSUE TITLE
Don't refresh the scene if the update transaction failed

### ISSUE THREAD

**Issue by LeonNicholls** [tz1and/tezland-issues#105]
I placed various items and then did an update. Unfortunately, the transaction got backtracked, but the scene got refreshed and all the items I placed disappeared. Rather give me another chance to do the update.

**Comment by 852Kerfunkle** [comment]
Sorry about that. Will be done,

Did the transaction show as failed? Just wondering - never really quite sure if that works or not. Kinda difficult to test.

**Comment by LeonNicholls** [comment]
Now I'm not sure if it showed a failure on tz1and. I do remember going to tzkt.io and seeing it was backtracked.

**Comment by 852Kerfunkle** [comment]
There's some stuff with the two block finality that makes things a bit tricky, but looking at your operation history, there were some backtracked due to errors. I'll look into it soon.

**Comment by 852Kerfunkle** [comment]
Made some changes for 0.5.15, please let me know if it's an improvement.

**Comment by 852Kerfunkle** [comment]
I *think* this is fixed.

**Comment by LeonNicholls** [comment]
Tricky to test since I haven't seen any blockchain issues recently, but will keep an eye out.
