### ISSUE TITLE
octrees for collisions and checking item intersections with places

### ISSUE THREAD

**Issue by AliaK77** [tz1and/tezland-issues#25]
octrees for collisions and checking item intersections with places. pretty sure it should do it for collisions already

**Comment by 852Kerfunkle** [comment]
The player collision with the place bounds is currently based on the bounding box only (I haven't quite figured out how to make it exact, but I'm confident it's possible, maybe need to force octrees on place bounds?). It can happen that you "enter" another place even if you are technically in your own.

**Comment by 852Kerfunkle** [comment]
Pretty sure this is done
