### ISSUE TITLE
initial map loading improvements

### ISSUE THREAD

**Issue by AliaK77** [tz1and/tezland-issues#37]
- further improve initial map loading: 
- Not queuing them all together maybe, but loading them slowly and deliberately, and being able to cancel queued places. 

  + maybe also serialise item loading in some way. rather: implement a way to prevent downloading the same item multiple times.

**Comment by 852Kerfunkle** [comment]
Some improvements in 0.5.0.

**Comment by 852Kerfunkle** [comment]
Considering this done in 0.5.x.
