### ISSUE TITLE
a tool that allows you to turn images into glb models with simple frames, with some options

### ISSUE THREAD

**Issue by AliaK77** [tz1and/tezland-issues#82]
a tool that allows you to turn images into glb models with simple frames, with some options
for people to display art in their Place

**Comment by 852Kerfunkle** [comment]
@NoRulesJustFeels made one, currently working on dockerising and getting it up into prod.

https://github.com/tz1and/image-framer

**Comment by 852Kerfunkle** [comment]
it's running in prod now
